### ISSUE TITLE
Some URLs problems

### ISSUE THREAD

**Issue by Ventricule** [dweidner/kirby-comments#3]
Hello !

Thanks for your plugin, it look GREAT and so usefull.

I install it but I have some issues with redirections. 
On localhost, when you install, every steps redirect to an url where the root directory is repeated 2 times. For exemple if the correct adress is "http://localhost/mysite/plugins/comments/install" it fail on "http://localhost/mysite/mysite/plugins/comments/install/2". I complete the installation by manually remove de repeated directory on each step.

Afterwhat, the problem is opposite : the root directory lack in urls. For exemple the plugin call "http://localhost/api/pages/pfx95r/comments/create" instead of "http://localhost/mysite/api/pages/pfx95r/comments/create".

Sure the solution is simple, but can't find it.

**Comment by dweidner** [comment]
Sorry, I must have missed the notification for your issue. I will have a closer look see if I can recreate your problem.

**Comment by dweidner** [comment]
Thank you for reporting the issue. The path detection of the installation wizard was confused by your subfolder setup. I fixed the problem. 

Furthermore I fixed the path to the API endpoint in the comment form, which was using a relative instead of an absolute path.

I am curious. Are you using this plugin in a production environment?
